### ISSUE TITLE
Can't run image with OAI key insertion through terminal:  Error: No such option: -e - 

### ISSUE THREAD

**Issue by KDragHowdy** [WaywardHayward/autogen-studio-dockerfile#2]
when trying to run the built image with "docker run -it --rm -p 8081:8081 autogenstudio -e "OPENAI_API_KEY='yourkey" get the error:

Error: No such option: -e
(autogenstudio) #:~/lrepos/autogen_docker$ autogenstudio ui --help
Usage: autogenstudio ui [OPTIONS]

  Launch the AutoGen Studio UI CLI .Pass in parameters host, port, workers,
  and reload to override the default values.

Options:
  --host TEXT         [default: 127.0.0.1]
  --port INTEGER      [default: 8081]
  --workers INTEGER   [default: 1]
  --reload
  --docs / --no-docs  [default: no-docs]
  --help              Show this message and exit.

**Comment by arukaen** [comment]
The command should actually be:

```
docker run -it --rm -p 8081:8081 -e "OPENAI_API_KEY=your_openai_api_key" autogenstudio
```
